### ISSUE TITLE
Subscribed to quarterly after login it doesn't give me access to courses

### ISSUE THREAD

**Issue by ivanbuncic** [fireship-io/fireship.io#108]
Hi, 
I subscribed quarterly, but after I logged in, I can not access courses, it says - choose a plan.

Am I deleted?

Cheers, 
Ivan

Link to invoice -- > https://dashboard.stripe.com/emails/receipts/invrc_1EIxpXBF7AptWZlcrWvy9L2h

**Comment by codediodeio** [comment]
Sent you a private message on twitter, let's chat over there.

**Comment by ivanbuncic** [comment]
Thank you!
