### ISSUE TITLE
Questions regarding the licensing of the project.

### ISSUE THREAD

**Issue by mattgcc** [fireship-io/fireship.io#111]
Hello,

May I get some clarification on how is this projected licensed? Firebase host said that it's open-source in his presenting video, yet there's no license listed. Is it public-sourced? Is it open to modification? Can we fork the project? How do we need to attribute the author?

Thanks,
Matt

**Comment by mrechung** [comment]
I would also like to know the license of this repo. Thanks.

**Comment by hwalyonglance** [comment]
?

**Comment by overlineink** [comment]
Hi @gccltl @eddyzerotoappstore @hwalyonglance ,

If you want to contribute for this project just check out the [style guide](https://fireship.io/style-guide/).

You all are free to fork this repo and make changes you want, depending on your intentions with the project I recommend to check the "Content Copyright Policy" section in web site [terms]( https://fireship.io/terms/).
