### ISSUE TITLE
Paid Contents Can be Opened in IE, No Payment Required at all

### ISSUE THREAD

**Issue by debottam31** [fireship-io/fireship.io#139]
@codediodeio Please open this site in Internet Explorer to get the understanding of the scenario. I can watch all your Pro Member videos in Internet Explorer for Free.

PS: I am a Pro Member and thanks for all your content on Youtube and Fireship

**Comment by codediodeio** [comment]
Thank you for pointing this out 👍 There was a little regression that was overlooked, but it was fixed on the last commit.
