### ISSUE TITLE
Added to Awesome SvelteKit

### ISSUE THREAD

**Issue by janosh** [fireship-io/fireship.io#1451]
Just a note that Fireship [was added to](https://github.com/janosh/awesome-sveltekit/pull/85) `awesome-sveltekit`.

https://janosh.github.io/awesome-sveltekit/fireship

Let me know if you'd like any changes to the data. If not, feel free to close.

**Comment by HannesEnnemann** [comment]
<img width="1440" alt="Screenshot 2023-01-12 at 1 21 07 pm" src="https://user-images.githubusercontent.com/122324909/211960651-94e9179f-66da-4ded-bb8c-dd892a495560.png">

**Comment by janosh** [comment]
@HannesEnnemann Thanks for the hint. The site has moved to GitHub Pages in the meantime. I updated the above link.

**Comment by HannesEnnemann** [comment]
Thanks @janosh
