### ISSUE TITLE
Can't access Fireship.io website from a West African region specifically Nigeria

### ISSUE THREAD

**Issue by henzyd** [fireship-io/fireship.io#1538]
I keep getting this every time I want to access fireship.io from Nigeria.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/97889189/231888047-bc9b0cab-ef29-47e0-adaf-d61d662eda31.png">

**Comment by HachemOuanes** [comment]
Have you tried accessing it using a VPN and choosing a different country?

**Comment by Ahonkhai** [comment]
Try another browser. I'm in Nigeria and it works for me

**Comment by henzyd** [comment]
Hmmm It's working now but it wasn't working before
