### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by Rabin-Osti** [fireship-io/fireship.io#1540]
I wanted to report a broken link on the page https://fireship.io/lessons/api-monetization-stripe/. The link text "Stripe JavaScript Course" appears to be broken. Clicking on the link results in a "404 Not Found" error.

**Comment by sklbz** [comment]
i think that the link that should go here is https://fireship.io/courses/stripe-js/

**Comment by StanleyY7** [comment]
I tested the link today, it has been fixed

**Comment by keenpaul29** [comment]
@admin please close this issue, it has been solved

**Comment by Rabin-Osti** [comment]
The issue has been solved.
