### ISSUE TITLE
Typo/Bug in Cloud Functions Masterclass Course

### ISSUE THREAD

**Issue by isurendrasingh** [fireship-io/fireship.io#16]
There is a typo in course layout & also one lesson is not uploaded correctly and one lesson is duplicated.

![screenshot 4](https://user-images.githubusercontent.com/7621607/50878844-8e357600-13fe-11e9-8a16-c43ca7ae6f66.png)

**Lesson 14 is Duplicate of lesson 10**

**Lesson 14 & 15 is not uploaded correctly**

**Comment by codediodeio** [comment]
Thank you! I have a fix for this incoming.

**Comment by isurendrasingh** [comment]
The lesson 14 issue was fixed. Thanks, but there is no **lesson 15**.

![image](https://user-images.githubusercontent.com/7621607/51014170-493f4a00-158c-11e9-871f-834b5db68c35.png)
