### ISSUE TITLE
Feature Request: Please add `id` to "Chapters" h2

### ISSUE THREAD

**Issue by gmlewis** [fireship-io/fireship.io#1628]
If `id="chapters"` is added to the "Chapters" `h2`, then students could more easily bookmark that section of the course in order to later jump right to it.
Thank you!

**Comment by kevinlu1248** [comment]
Hey, I just fixed this at https://github.com/fireship-io/fireship.io/pull/1632 using Sweep, an AI junior dev (https://github.com/sweepai/sweep).

You can also leave comments at https://github.com/kevinlu1248/fireship.io/pull/16 for Sweep to fix things.

**Comment by kevinlu1248** [comment]
@codediodeio Thanks for the merge! Would love it if Sweep could be installed directly on this repo! (more details at https://github.com/fireship-io/fireship.io/issues/1629)
