### ISSUE TITLE
Configuring my own stripe products

### ISSUE THREAD

**Issue by leoMedfy** [fireship-io/fireship.io#1676]
Hi Jeff and everyone from the amazing Fireship community! 

I'm a developer from Brazil, and I recently purchased some courses on the Fireship.io platform (Been an avid fan of the YouTube channel for a few years) and I fell in love with it. I'm playing around creating my own courses, and products in my Stripe account, however, when I try to check-out I get a toast saying "Error: No such price 'price_anyPriceId' ". Is there anything that you guys could share on creating my own products? I couldn't find a stripe configuration file, or any further instructions on setting up the project per se.

Thank you guys so much! Sending a lot of love from Brazil! Cheers!

**Comment by leoMedfy** [comment]
Maybe it's an .env issue? I really have no idea on the setup proccess for now, hahaha 🥲

**Comment by aikooo7** [comment]
Hello @leoMedfy, probably you did some typo error? 
OR
you need to do "'price_anyPriceId" price in your product.

Regards,
aikoo7, much love from portugual.

**Comment by leoMedfy** [comment]
Unfortunately there is no typo, I put the price id directly from Stripe where it should be, and I still get the error, like:
    'nextjs': {
        id: 'nextjs',
        price: 'price_XXXXXXXXXX',
        amount: 20,
    },

And still get the error when trying to open it.

**Comment by leoMedfy** [comment]
It seems that there's an error 500 when trying to buy the course: Failed to load resource: the server responded with a status of 500 () "https://us-central1-fireship-app.cloudfunctions.net/userAPI"
