### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by syedbarimanjan** [fireship-io/fireship.io#1717]
I sent an email to hello@fireship.io regarding the bug please respond to it.
my email is syedbarimanjan@gmail.com

**Comment by IbrahimAlshubaily** [comment]
How?

**Comment by syedbarimanjan** [comment]
Who are you?

**Comment by SaschaLucius** [comment]
this is already known for a while https://github.com/fireship-io/fireship.io/issues/1495

**Comment by IbrahimAlshubaily** [comment]
> Who are you?

Good thanks - who are you?
