### ISSUE TITLE
Wrong thumbnail on course/next.js full course

### ISSUE THREAD

**Issue by ken-man-lk** [fireship-io/fireship.io#1731]
- **Issues:**  wrong thumbnail on course/next.js full course, the thumbnail should be update to nextjs 14

![Screenshot 2024-04-01 at 12 38 29 AM](https://github.com/fireship-io/fireship.io/assets/88052499/6609b231-7972-4638-865a-d528f28ed552)

![Screenshot 2024-04-01 at 12 38 43 AM](https://github.com/fireship-io/fireship.io/assets/88052499/9319700e-c013-4e1f-a0e6-74dd7b33846f)

**Comment by Mehdi-UX-Dev** [comment]
no updates yet?
