### ISSUE TITLE
Shortcut for search

### ISSUE THREAD

**Issue by blenderskool** [fireship-io/fireship.io#22]
As the entire site is mainly built for developers with an amazing design resembling an editor, how about adding a shortcut that can open the search window? Something like <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> would be super helpful when browsing the site through keyboard :slightly_smiling_face:

**Comment by codediodeio** [comment]
I like this and it would be easy to in the `algolia-button` component. We should also bind the the esc key to close the search.

**Comment by blenderskool** [comment]
@codediodeio Can I try working on this?

**Comment by codediodeio** [comment]
Yes, please do. I think the best approach is to setup hostlisteners here https://github.com/fireship-io/fireship.io/blob/master/components/src/app/algolia/algolia-search/algolia-search.component.ts. Something like:

```
@HostListener('document:keydown.escape', ['$event']) onSearchClose(event: KeyboardEvent) {
    this.toggle(false)
}
```
