### ISSUE TITLE
RSS Feed?

### ISSUE THREAD

**Issue by sleepinzombie** [fireship-io/fireship.io#241]
I've been browsing through the website for news with different tags.

I was thinking maybe you can provide an option for using RSS to plug in different feeds in a RSS reader app.

**Comment by okyanusoz** [comment]
Hi there,
There is an RSS feed for Fireship. It can be found [here](https://fireship.io/index.xml).

**Comment by sleepinzombie** [comment]
@okyanusoz Okay noted, thank you for the link! I'll try it with Reeder.

**Comment by sleepinzombie** [comment]
I think this issue can be closed.
