### ISSUE TITLE
typo in page https://fireship.io/lessons/sharing-data-between-angular-components-four-methods/

### ISSUE THREAD

**Issue by leoinlios** [fireship-io/fireship.io#267]
Hi - thanks for fireship.io, great content. 

I think you have a typo in: 
https://fireship.io/lessons/sharing-data-between-angular-components-four-methods/

You stated: which can be listed to by the parent
I think you meant: which can be **_listened_** to by the parent

Thanks
L

**Comment by Robogeek95** [comment]
Sent a PR
