### ISSUE TITLE
Help Needed in setting up this project 

### ISSUE THREAD

**Issue by namanr** [fireship-io/fireship.io#335]
i need help in running this project , did cloned this project in my local , run  npm install
it gives
```
npm WARN ajv-keywords@3.5.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. 
You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\firebase-tools\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1545 packages in 31.393s

32 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (2 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```
then run , npm run dev , and nothing happen .

i am new to angular and firebase , my question may sound bit awkward , but  i am expecting your help, i really admire this website and i want to learn from this website .

additionally , i have already installed hugo in my local ,

**Comment by namanr** [comment]
Sol: I had executed ```npm config set ignore-scripts true,  for security reasons```, i changed it to false and everything starts working

**Comment by vivekbirana** [comment]
hello  i would line to know how to manage the content of the pages
does it have a admin panel?

**Comment by namanr** [comment]
no it does not have any admin pannel , just go to hugo/content

**Comment by akhil-naidu** [comment]
@namanr As the issue started, I'm also the facing the same issues, and according to the discussions this should be the order, if not please let me know

1. Install Hugo locally
2. `npm config set ignore-scripts false`
3. `npm install` or `npm install --no-audit`
4. `npm run dev`

So these will give a working website on the port 1313, and for any changes, I should use hugo/content directory and use markdown editor to proceed further.

**Comment by etzl** [comment]
@namanr If your problem is solved please close this issue

**Comment by namanr** [comment]
done
