### ISSUE TITLE
Slack link is dead

### ISSUE THREAD

**Issue by GunnerBasil** [fireship-io/fireship.io#347]
https://fireship.page.link/slack leads to an invalid invite.

**Comment by martinmoose** [comment]
It says you need a @fireship.com mail, but i don't know how to get one?

**Comment by GunnerBasil** [comment]
I don't think you can.

**Comment by codediodeio** [comment]
Slack expired the link, please give it a try now :)

**Comment by GunnerBasil** [comment]
thanks!

**Comment by jay-jlm** [comment]
@codediodeio I can't join either.
