### ISSUE TITLE
Reposition "Watch" button in Website

### ISSUE THREAD

**Issue by Akshu-on-github** [fireship-io/fireship.io#365]
The watch button in question is captured in the bottom of the screenshot:

![image](https://user-images.githubusercontent.com/61582763/103133419-5188e500-46d0-11eb-9e64-4767af085faf.png)

The line spacing is off due to the alignment of the "Watch" button. I'd suggest applying a line break and centering it

**Comment by pseudo-usama** [comment]
Can you share the link for this page?

**Comment by okyanusoz** [comment]
@pseudo-usama I think the home page: https://fireship.io
