### ISSUE TITLE
Default Avatar 

### ISSUE THREAD

**Issue by Robogeek95** [fireship-io/fireship.io#380]
In a case where the image is not found or the source URL is incorrect

A use case is on the contributor page i.e https://fireship.io/contributors/lenny-cunningham/ 

![Screen Shot 2021-02-04 at 00 43 12](https://user-images.githubusercontent.com/29512699/106824388-0674d100-6683-11eb-98f8-fbcd8a96fbb9.png)

Here the contributor's image link is broken, there could be a default avatar to fill the spot

**Comment by pseudo-usama** [comment]
This issue is resolved. Close this one.

**Comment by Robogeek95** [comment]
Sure thanks
