### ISSUE TITLE
Speed setting on videos cannot be altered

### ISSUE THREAD

**Issue by jaipresto** [fireship-io/fireship.io#43]
The speed setting on the video player seems to be unchangeable. I've tried various browsers but the problem persists. As a temp fix I've been using opening the src link of the video-player directly from the source code in a new tab, and using the Video Speed Controller chrome extension.

**Comment by codediodeio** [comment]
This is related to #36 - basically, it looks like the entire video player will need to be refactored, but should have fixes next week.
