### ISSUE TITLE
no delete button

### ISSUE THREAD

**Issue by JOduMonT** [fireship-io/fireship.io#463]
it seams impossible to delete my account
https://fireship.io/dashboard/subscription/

**Comment by TheManuz** [comment]
I'm having the same issue.

I signed up with Google because "sign up to read", just to read an article... too bad after signing up the "sign up to read" became a "subscribe to pro to read".

Not fair, almost scammy.

So I want to delete my account, but the delete function is nowhere to be found.

**Comment by codediodeio** [comment]
Some videos are free after logging in, while others are paid. I'll try to make this more clear on the UI before clicking the button. 

Complete account deletion can be handled via email request hello@fireship.io
