### ISSUE TITLE
SEO: Use descriptive text in links

### ISSUE THREAD

**Issue by brijmcq** [fireship-io/fireship.io#48]
Currenly, Lighthouse score for SEO is 91. We can probably make it to 100 if we update the text to something else.

![image](https://user-images.githubusercontent.com/13441420/51220664-1d97d780-1971-11e9-8b54-d6035339309f.png)

More info: 
https://developers.google.com/web/tools/lighthouse/audits/descriptive-link-text

**Comment by codediodeio** [comment]
Thank you :+1: I am all for this if you want to PR a better description.

**Comment by MrExpert** [comment]
I would like to take on this if it is still not done.  where should i start?
