### ISSUE TITLE
Blocked video in Indonesia

### ISSUE THREAD

**Issue by TimotiusAnrez** [fireship-io/fireship.io#486]
Hi, I am intrigued about fireship and decided to give myself a try. However I can't watch some of the video on the course section since the video is blocked in my country (Indonesia). Could anyone take a look at this issue?

**Blocked**
![image](https://user-images.githubusercontent.com/71978054/134708966-9c4c4ae7-4233-4cd8-ab4a-b607f016c8e8.png)
![image](https://user-images.githubusercontent.com/71978054/134709110-b4d94bce-4443-4779-97d3-0e9f3a5f09d7.png)
![image](https://user-images.githubusercontent.com/71978054/134709191-83679229-2e91-47e0-bad2-b20a60da11d2.png)
![image](https://user-images.githubusercontent.com/71978054/134709488-2771bd9d-e96b-43d6-990c-e24da310a80a.png)

**Working**
![image](https://user-images.githubusercontent.com/71978054/134709300-778f6299-6cf1-40ce-91ad-561d060ecd7d.png)
![image](https://user-images.githubusercontent.com/71978054/134709379-fc3f33e2-e63b-4b80-9849-a42c1f27f890.png)

**Comment by Gokaran505** [comment]
Did you try it on a different browser?
