### ISSUE TITLE
I lose 300 USD paying with crypto

### ISSUE THREAD

**Issue by Ignaciojeria** [fireship-io/fireship.io#488]
update my subscription paying with crypto, how long should I wait for it to be activated?

my email : ignaciovl.j@gmail.com
transaction ID : 0x56515655072e0cb61f4e242ce96a0ae9849e38b1

![image](https://user-images.githubusercontent.com/22633129/135149834-9dcbbed8-17a0-431e-b3cc-56619ee587d0.png)

BscScan detail:
![image](https://user-images.githubusercontent.com/22633129/135150132-befa05f0-127b-43f5-ad1d-4db059c8c39f.png)

My dashboard:
![image](https://user-images.githubusercontent.com/22633129/135150246-2701e90b-71ed-496f-893f-18abf12fbd5e.png)

**Comment by codediodeio** [comment]
I see the request, but no actual payments attached to it
<img width="463" alt="Screen Shot 2021-09-28 at 12 19 24 PM" src="https://user-images.githubusercontent.com/10172199/135152170-ec75fb4e-ad8a-4c79-b8c5-7b67fab22000.png">

**Comment by Ignaciojeria** [comment]
will it be a coinbase problem? Have I done something wrong?

Im going to reproduce steps: 

Step 1 I choose lifetime subscription: 

![image](https://user-images.githubusercontent.com/22633129/135155418-547f57c6-3361-4727-a1ca-6c7c9b166de1.png)

Step 2 I choose pay with cripto : 

![image](https://user-images.githubusercontent.com/22633129/135155665-fbdc01e2-1ca7-4756-b06e-8abc436d241b.png)

Step 3 I send 300 USDC to direction indicated by coinbase: 
![image](https://user-images.githubusercontent.com/22633129/135156037-ce6c4e39-f94a-4b7b-86e2-5c8cc206cea9.png)

My wallet :

![image](https://user-images.githubusercontent.com/22633129/135156167-f95569e4-8525-4914-aedc-73f7534e2290.png)

![image](https://user-images.githubusercontent.com/22633129/135156202-b702020d-0b15-4f79-8b8d-d06c360fc705.png)

**Comment by Ignaciojeria** [comment]
Other thing that does not work is the discount coupon using crypto payment : 

![image](https://user-images.githubusercontent.com/22633129/135156701-fbdeed55-0e0a-4af9-b5dc-967afc40b8c2.png)

![image](https://user-images.githubusercontent.com/22633129/135156796-5aa0f219-cbd1-4abf-988a-abb8b7bb85c8.png)

**Comment by codediodeio** [comment]
That's interesting, it appears this must be an issue with Coinbase. I wonder if there's a delay recognizing the payment. First time I've seen an issue with a crypto payment, I'll update your pro status for now. 

I just contacted Coinbase support. Sorry about that.

**Comment by Ignaciojeria** [comment]
Sorry for being that insistent. Thank you for addressing my issue and I hope the payment issues can be resolved from Coinbase.

**Comment by codediodeio** [comment]
From Coinbase "After a close review of the transaction, it appears this payment was made with a network that Coinbase Commerce currently does not support. We do not support BEP2/BEP20 and we do not have access to these funds.

Only supported networks can be accepted on Coinbase Commerce and they must be sent to the correct wallet address through the supported blockchain. 
 
If an unsupported network is sent to Coinbase Commerce, then there is no way for Coinbase to recover those funds."

**Comment by codediodeio** [comment]
I'll provide access, but looks like the funds are lost

**Comment by Ignaciojeria** [comment]
Okay, in that case, I wouldn't know how to proceed. Would I have to speak
to Coinbase directly to try to get the funds back, or do I keep the
subscription and forget the problem?

**Comment by codediodeio** [comment]
You can keep the subscription :) if you manage to get funds back that would be great, but not sure if that's possible.
