### ISSUE TITLE
I bought the lifetime access with the wrong email...

### ISSUE THREAD

**Issue by tuanminh160302** [fireship-io/fireship.io#545]
My email is canhtuan09@gmail.com but I made a typo when purchasing the lifetime access and instead typed in canhtuan09@gmai.com. Can I get my email changed back to canhtuan09@gmail.com?
![272378204_256894336572639_7570834223993078231_n](https://user-images.githubusercontent.com/51919628/150673128-5b42f2cf-b3d7-44d9-a0fa-07e6900c9f4c.png)
![271830146_238041745054135_1160165319563742147_n](https://user-images.githubusercontent.com/51919628/150673097-d890ced6-51ab-4889-b352-c9e8ae2ee4fe.png)

**Comment by Ashish2097** [comment]
There should be a help and support option on the website.

**Comment by Xedera** [comment]
> My email is [canhtuan09@gmail.com](mailto:canhtuan09@gmail.com) but I made a typo when purchasing the lifetime access and instead typed in [canhtuan09@gmai.com](mailto:canhtuan09@gmai.com). Can I get my email changed back to [canhtuan09@gmail.com](mailto:canhtuan09@gmail.com)? ![272378204_256894336572639_7570834223993078231_n](https://user-images.githubusercontent.com/51919628/150673128-5b42f2cf-b3d7-44d9-a0fa-07e6900c9f4c.png) ![271830146_238041745054135_1160165319563742147_n](https://user-images.githubusercontent.com/51919628/150673097-d890ced6-51ab-4889-b352-c9e8ae2ee4fe.png)

tag the developer to help you

**Comment by codediodeio** [comment]
Hey @Xedera Upgraded your account for life, thank you! In you need anything in the future, email hello@fireship.io or join our Slack channel.
