### ISSUE TITLE
Cancelled membership during valid period

### ISSUE THREAD

**Issue by odiraneyya** [fireship-io/fireship.io#549]
Hello.

I am not a fan of auto renewals. This is why I usually cancel my membership immediately after in order to avoid it renewing without my consent. This usually works as intended. Unfortunately on fireship.io, this lead to deactivating my pro membership immediately.
![image](https://user-images.githubusercontent.com/66945713/150706106-0693e93a-1cab-4abc-b530-32008a48f64c.png)
![image](https://user-images.githubusercontent.com/66945713/150706178-b86dffc9-50f1-4a3f-9e5b-858c72c2ec87.png)

As can be seen above. This did not work above which to me seems like a bug.

Can you please restore my premium membership and disable auto renewal.

Thanks.
Orwa.

**Comment by codediodeio** [comment]
Hey Orwa, sorry about that. Can you please email hello@fireship.io so I can extend your access. I need your email address.
