### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by ketanchoyal** [fireship-io/fireship.io#77]
I'm not able to login through Google Chrome on desktop or mobile. I was able to login to the site through Safari browser but now video are not loading

**Comment by overlineink** [comment]
It was probably network problem. Try one more time @ketanchoyal

**Comment by donatoaguirre24** [comment]
I have the same problem and I already tried several times but the error persists.
![image](https://user-images.githubusercontent.com/20030075/52607578-75810b80-2e55-11e9-84da-915f75c75328.png)

**Comment by ketanchoyal** [comment]
The problem stays in chrome, try Safari it'll  work there
