### ISSUE TITLE
you can bypass the paywall an get free fireship pro

### ISSUE THREAD

**Issue by ChdML** [fireship-io/fireship.io#901]
elements with the `allow-if` tag can be bypassed, you just have to change the level from pro to user.
before:
![image](https://user-images.githubusercontent.com/74703393/184970085-a32edc05-ecb7-4de1-8b00-b575b58c82dd.png)
after:
![image](https://user-images.githubusercontent.com/74703393/184970386-0c7e3f3d-5013-423b-baa3-7a0603e2aa5c.png)

**Comment by EduardoU24** [comment]
confirmed 
![image](https://user-images.githubusercontent.com/1507317/185232100-fd19f2c6-1b55-4d04-be96-98715422b01a.png)

**Comment by ChdML** [comment]
Fixed in new the new fireship version

**Comment by DipHire** [comment]
> Fixed in new the new fireship version

No it's still not fixed!!
